name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Hacer commit si las pruebas pasan
        if: success()
        run: |
          git config --local user.email "roddyrichiez44@github.com"
          git config --local user.name "roddyrichiez"
          git commit -am "Pruebas unitarias pasadas por GitHub Actions"
          git push
